/* THIS FILE IS AUTO-GENERATED BY Unidesk.Client.ModelGenerator */
/* DO NOT EDIT */
/* GENERATED ON 2022-09-20 17:24:23 */

export const Update_User_Functions = "Update_User_Functions";

export const All = [
    Update_User_Functions,
];
