/* THIS FILE IS AUTO-GENERATED BY Unidesk.Client.ModelGenerator */
/* DO NOT EDIT */
/* GENERATED ON 2022-09-23 18:27:56 */

export const Unknown = "Unknown";
export const Team = "Team";
export const Organization = "Organization";

export const All = [
    Unknown,
    Team,
    Organization,
];
