/* THIS FILE IS AUTO-GENERATED BY Unidesk.Client.ModelGenerator */
/* DO NOT EDIT */
/* GENERATED ON 2022-09-28 17:31:46 */

export const Unknown = {"cze":"Nezn\u00E1m\u00FD","eng":"Unknown","value":"Unknown"};
export const Owner = {"cze":"Vlastn\u00EDk","eng":"Owner","value":"Owner"};
export const Editor = {"cze":"Editor","eng":"Editor","value":"Editor"};
export const Viewer = {"cze":"Pouze pro \u010Dten\u00ED","eng":"Viewer","value":"Viewer"};
export const Member = {"cze":"\u010Clen","eng":"Member","value":"Member"};

export const All = [
    Unknown,
    Owner,
    Editor,
    Viewer,
    Member,
];
