/* THIS FILE IS AUTO-GENERATED BY Unidesk.Client.ModelGenerator */
/* DO NOT EDIT */
/* GENERATED ON 2022-09-08 19:40:55 */

export const Draft = {"cze":"N\u00E1vrh","eng":"Draft","value":"Draft"};
export const New = {"cze":"Nov\u00E9","eng":"New","value":"New"};
export const Reserved = {"cze":"Rezervovan\u00E9","eng":"Reserved","value":"Reserved"};
export const Assigned = {"cze":"P\u0159i\u0159azeno","eng":"Assigned","value":"Assigned"};
export const Submitted = {"cze":"Odevzd\u00E1no","eng":"Submitted","value":"Submitted"};
export const Finished_Susccessfully = {"cze":"\u00DAsp\u011B\u0161n\u011B dokon\u010Deno","eng":"Finished Successfully","value":"Finished_Susccessfully"};
export const Finished_Unsuccessfully = {"cze":"Ne\u00FAsp\u011B\u0161n\u011B dokon\u010Deno","eng":"Finished Unsuccessfully","value":"Finished_Unsuccessfully"};
export const Finished = {"cze":"Dokon\u010Deno","eng":"Finished","value":"Finished"};
export const Abandoned = {"cze":"Preru\u0161eno","eng":"Abandoned","value":"Abandoned"};
export const Unknown = {"cze":"Nezn\u00E1m\u00FD","eng":"Uknown","value":"Unknown"};

export const All = [
    Draft,
    New,
    Reserved,
    Assigned,
    Submitted,
    Finished_Susccessfully,
    Finished_Unsuccessfully,
    Finished,
    Abandoned,
    Unknown,
];
