/* THIS FILE IS AUTO-GENERATED BY Unidesk.Client.ModelGenerator */
/* DO NOT EDIT */
/* GENERATED ON 2022-09-06 17:50:55 */

export const User_SuperAdmin = {"name":"User_SuperAdmin","description":"Super Admin","id":"4bffef59-a0f2-428d-921a-a4e55cef7ca0"};
export const User_Admin = {"name":"User_Admin","description":"Admin","id":"6d38d901-b11e-47f3-bc7e-b6d0f57d776d"};
export const User_Teacher = {"name":"User_Teacher","description":"Teacher","id":"908f82e0-f5b2-41ac-9c62-60d25b49c99b"};
export const User_Student = {"name":"User_Student","description":"Student","id":"2870eca9-ee10-4406-a3a0-ad23f8a03185"};
export const User_Guest = {"name":"User_Guest","description":"Guest","id":"07e6e5b4-8e31-411a-9ed9-26ec462984cc"};
export const Action_Merge_Keywords = {"name":"Action_Merge_Keywords","description":"Merge Keywords","id":"10018290-58ef-4bc9-b5b8-3d93dcb07805"};

export const All = [
    User_SuperAdmin,
    User_Admin,
    User_Teacher,
    User_Student,
    User_Guest,
    Action_Merge_Keywords,
];
