/* THIS FILE IS AUTO-GENERATED BY Unidesk.Client.ModelGenerator */
/* DO NOT EDIT */
/* GENERATED ON 2022-09-20 18:12:59 */

export const None = "None";
export const Guest = "Guest";
export const Author = "Author";
export const Teacher = "Teacher";
export const Admin = "Admin";
export const Supervisor = "Supervisor";
export const Opponent = "Opponent";

export const All = [
    None,
    Guest,
    Author,
    Teacher,
    Admin,
    Supervisor,
    Opponent,
];
