/* THIS FILE IS AUTO-GENERATED BY Unidesk.Client.ModelGenerator */
/* DO NOT EDIT */
/* GENERATED ON 2022-09-28 17:31:46 */

export const Unknown = {"cze":"Nezn\u00E1m\u00FD","eng":"Unknown","value":"Unknown"};
export const Accepted = {"cze":"Schv\u00E1len\u00FD","eng":"Accepted","value":"Accepted"};
export const Declined = {"cze":"Odm\u00EDtnut\u00FD","eng":"Declined","value":"Declined"};
export const Removed = {"cze":"Odstran\u011Bn\u00FD","eng":"Removed","value":"Removed"};
export const Pending = {"cze":"\u010Cekaj\u00EDc\u00ED na schv\u00E1len\u00ED","eng":"Pending","value":"Pending"};

export const All = [
    Unknown,
    Accepted,
    Declined,
    Removed,
    Pending,
];
