/* THIS FILE IS AUTO-GENERATED BY Unidesk.Client.ModelGenerator */
/* DO NOT EDIT */
/* GENERATED ON 2022-09-08 19:51:46 */

export const Yes = {"cze":"Ano","eng":"Yes","value":"Yes"};
export const No = {"cze":"Ne","eng":"No","value":"No"};

export const All = [
    Yes,
    No,
];
